name: Manual

on: 
  workflow_dispatch:
    inputs:
      version:
        description: Version
        default: v1.0.0
        required: true

jobs:
  build:
    name: Manual
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    
    steps:
      - name: Checking out code
        uses: actions/checkout@v2
      - name: Change dir to action
        working-directory: action
        run: pwd
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm start
